# Generated by Django 3.2.8 on 2021-11-14 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lecture_topic', models.CharField(max_length=100)),
                ('lecture_date', models.CharField(max_length=100)),
                ('attendaces', models.CharField(max_length=2)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.classes')),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.course')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.student')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_name', models.CharField(max_length=100)),
                ('total_marks', models.IntegerField()),
                ('file', models.FileField(upload_to='')),
                ('end_date', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('submission', models.CharField(max_length=50)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.classes')),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.course')),
            ],
        ),
    ]
