# Generated by Django 3.1.7 on 2021-04-01 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_roll_number', models.CharField(max_length=100)),
                ('total_marks', models.IntegerField()),
                ('obtained_marks', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
                ('submission', models.CharField(max_length=50)),
                ('assignment_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.assignment')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.classes')),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.course')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.student')),
            ],
        ),
    ]
